name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t docker.pkg.github.com/chappio/discovery.chapp.io/discovery_server:latest
