name: Main
on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]
  release:
    types: [published]

jobs:
  deploy:
    name: Publish docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push to GitHub packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: chappio/discovery.chapp.io/discovery_server
          tag_with_ref: true
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: chappio/discovery_server
          tag_with_ref: true
